// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MainItf is an autogenerated mock type for the MainItf type
type MainItf struct {
	mock.Mock
}

// Process provides a mock function with given fields: num1, num2, callback
func (_m *MainItf) Process(num1 int, num2 int, callback func(int, int) (int, error)) (int, error) {
	ret := _m.Called(num1, num2, callback)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, func(int, int) (int, error)) (int, error)); ok {
		return rf(num1, num2, callback)
	}
	if rf, ok := ret.Get(0).(func(int, int, func(int, int) (int, error)) int); ok {
		r0 = rf(num1, num2, callback)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, func(int, int) (int, error)) error); ok {
		r1 = rf(num1, num2, callback)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMainItf creates a new instance of MainItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMainItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MainItf {
	mock := &MainItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
