// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SubItf is an autogenerated mock type for the SubItf type
type SubItf struct {
	mock.Mock
}

// AnotherProcess provides a mock function with given fields: num1, num2
func (_m *SubItf) AnotherProcess(num1 int, num2 int) (int, error) {
	ret := _m.Called(num1, num2)

	if len(ret) == 0 {
		panic("no return value specified for AnotherProcess")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int, error)); ok {
		return rf(num1, num2)
	}
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(num1, num2)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(num1, num2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubItf creates a new instance of SubItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubItf {
	mock := &SubItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
